apiVersion: anthos-migrate.cloud.google.com/v1beta1
kind: Migration
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"anthos-migrate.cloud.google.com/v1beta1","kind":"Migration","metadata":{"annotations":{},"name":"pmml-migration","namespace":"default"},"spec":{"artifacts":{"dataVolumes":[{"folders":["\u003cfolder\u003e"],"pvcName":"pvc-pmml-vm"}],"deployment":{"appName":"app-pmml-vm","bucket":"esiemes-default-migration-artifacts","pathPrefix":"default-pmml-migration/"},"excludeFilters":["- *.swp","- /etc/fstab","- /boot/","- /tmp/*","- /var/log/*.log*","- /var/log/*/*.log*","- /var/cache/*"],"image":{"base":"gcr.io/esiemes-default/pmml-vm-non-runnable-base:v1.0.0","name":"gcr.io/esiemes-default/pmml-vm:v1.0.0"}},"intent":"ImageAndData","source":{"gce":{"labels":{"migration-cluster":"migration-processing","migration-name":"pmml-migration","migration-namespace":"default"},"project":"esiemes-default","vmId":"pmml-vm","zone":"us-central1-c"}}}}
  creationTimestamp: "2020-05-15T12:35:15Z"
  finalizers:
  - delete.disks.migration.finalizer
  generation: 2
  name: pmml-migration
  namespace: default
  resourceVersion: "384373"
  selfLink: /apis/anthos-migrate.cloud.google.com/v1beta1/namespaces/default/migrations/pmml-migration
  uid: 870085b6-96a8-11ea-b545-42010a8001cb
spec:
  artifacts:
    dataVolumes:
    - folders:
      - <folder>
      pvcName: pvc-pmml-vm
    deployment:
      appName: app-pmml-vm
      bucket: esiemes-default-migration-artifacts
      pathPrefix: default-pmml-migration/
    excludeFilters:
    - '- *.swp'
    - '- /etc/fstab'
    - '- /boot/'
    - '- /tmp/*'
    - '- /var/log/*.log*'
    - '- /var/log/*/*.log*'
    - '- /var/cache/*'
    image:
      base: gcr.io/esiemes-default/pmml-vm-non-runnable-base:v1.0.0
      name: gcr.io/esiemes-default/pmml-vm:v1.0.0
  configs: {}
  intent: ImageAndData
  source:
    gce:
      labels:
        migration-cluster: migration-processing
        migration-name: pmml-migration
        migration-namespace: default
      project: esiemes-default
      vmId: pmml-vm
      zone: us-central1-c
status:
  process: ""
  state: ""
  status: ""
  steps: null
