apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pmml-vm-pvc
spec:
  storageClassName: v2k-csi-gce-disk
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50G

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vls-pv-vls-4fba-pmml-vm
spec:
  storageClassName: ""
  capacity:
    storage: 50G
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    # Name of pd
    pdName: vls-4fba-pmml-vm
  volumeMode: Block
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vls-pvc-vls-4fba-pmml-vm
spec:
  storageClassName: ""
  volumeName: vls-pv-vls-4fba-pmml-vm
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50G
  volumeMode: Block

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: pmml-vm
  namespace: default
spec:
  serviceName: "pmml-vm-svc"
  replicas: 1
  selector:
    matchLabels:
      app: pmml-vm
  template:
    metadata:
      labels:
        app: pmml-vm
    spec:
      initContainers:
      - name: lister
        image: anthos-migrate.gcr.io/vls-runimg:v1.0.1
        imagePullPolicy: Always
        volumeMounts:
        - name: volumes
          mountPath: /volumes
        volumeDevices:
        - name: vls-4fba-pmml-vm
          devicePath: /devices/000-vls-4fba-pmml-vm

        env:
          - name: "HC_BOOT_DEVICE_NAME"
            value: "000-vls-4fba-pmml-vm"
          - name: "HC_DEVICES_DIR"
            value: "/devices"
          - name: "HC_DEVICES_LIST_DIR"
            value: "/volumes"
          - name: "HC_RUNNER_PARAMS"
            value: "listdevs"
      - name: init
        image: anthos-migrate.gcr.io/v2k-init:v1.0.1
        imagePullPolicy: Always
        env:
          - name: "HC_BLOCKDEV_MODE"
            value: "true"
          - name: "HC_TRIM_MOUNTS"
            value: "false"
          - name: "HC_VOLUME_PATH"
            value: "/volumes"
        volumeMounts:
        - name: volumes
          mountPath: /volumes
        - name: rootfs
          mountPath: /rootfs
        - name: lvmdata
          mountPath: /run/lvm
        - name: udevdata
          mountPath: /run/udev
        securityContext:
          privileged: true
      containers:
      - name: pmml-vm
        image: anthos-migrate.gcr.io/v2k-run:v1.0.1
        imagePullPolicy: Always
        volumeMounts:
        - name: rootfs
          mountPath: /rootfs
        - name: cgroups
          mountPath: /sys/fs/cgroup
        securityContext:
          privileged: true
        readinessProbe:
          exec:
            command:
            - /code/ready.sh
      volumes:
      - name: vls-4fba-pmml-vm
        persistentVolumeClaim:
          claimName: vls-pvc-vls-4fba-pmml-vm
          readOnly: false

      - name: volumes
        emptyDir: {}
      - name: rootfs
        persistentVolumeClaim:
          claimName: pmml-vm-pvc
          readOnly: false
      - name: lvmdata
        hostPath:
          path: /run/lvm
          type: Directory
      - name: udevdata
        hostPath:
          path: /run/udev
          type: Directory
      - name: cgroups
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
