apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"pvc-pmml-vm","namespace":"default"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"10G"}},"storageClassName":"retain-standard-ssd"}}
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/gce-pd
  creationTimestamp: "2020-05-15T12:35:15Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    migration: pmml-migration
    migration-namespace: default
    migration-uid: 870085b6-96a8-11ea-b545-42010a8001cb
  name: pvc-pmml-vm
  namespace: default
  resourceVersion: "381281"
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/pvc-pmml-vm
  uid: 873e0747-96a8-11ea-b545-42010a8001cb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10G
  storageClassName: retain-standard-ssd
  volumeMode: Filesystem
  volumeName: pvc-873e0747-96a8-11ea-b545-42010a8001cb
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  phase: Bound

---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubernetes.io/createdby: gce-pd-dynamic-provisioner
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/gce-pd
  creationTimestamp: "2020-05-15T12:35:19Z"
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    failure-domain.beta.kubernetes.io/region: us-central1
    failure-domain.beta.kubernetes.io/zone: us-central1-c
    migration: pmml-migration
    migration-namespace: default
    migration-uid: 870085b6-96a8-11ea-b545-42010a8001cb
  name: pvc-873e0747-96a8-11ea-b545-42010a8001cb
  resourceVersion: "381283"
  selfLink: /api/v1/persistentvolumes/pvc-873e0747-96a8-11ea-b545-42010a8001cb
  uid: 89638304-96a8-11ea-b545-42010a8001cb
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pvc-pmml-vm
    namespace: default
    resourceVersion: "381265"
    uid: 873e0747-96a8-11ea-b545-42010a8001cb
  gcePersistentDisk:
    fsType: ext4
    pdName: gke-migration-processi-pvc-873e0747-96a8-11ea-b545-42010a8001cb
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: failure-domain.beta.kubernetes.io/zone
          operator: In
          values:
          - us-central1-c
        - key: failure-domain.beta.kubernetes.io/region
          operator: In
          values:
          - us-central1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: retain-standard-ssd
  volumeMode: Filesystem
status:
  phase: Bound

---
